name: 'Hello Secrets!'
description: 'Log out hello Secret'
inputs:
  ssm_param_name:  # id of input
    description: 'Name of the Param'
    required: true
outputs:
  ssm_param_value: # id of output
    description: 'Value of the param'
runs:
  using: 'node16'
  main: 'index.js'
