on: [push]

jobs:
  test-export-environment-variables:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          path: '/shared/'
          prefix: 'REACT_APP_'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_ACCESS_KEY_ID_GHA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY_GHA }}
          AWS_DEFAULT_REGION: 'eu-west-1'
          AWS_ROLE_ARN: ${{ secrets.ORG_AWS_ROLE_ARN_GHA_DEVOPS }}

      - name: View vars
        run: echo "view"
