on: [push]

jobs:
  test-export-environment-variables:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          path: '/shared/'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
          AWS_ROLE_ARN: 'arn:aws:iam::463037328738:role/human/OZHumanAdmin'

      - name: View vars
        run: echo "view"
